ARG BASE_UBI_IMAGE_TAG=9.5-1742914212
FROM registry.access.redhat.com/ubi9/ubi-minimal:${BASE_UBI_IMAGE_TAG}

ARG PYTHON_VERSION=3.12

ENV VIRTUAL_ENV=/opt/venv
ENV PATH=${VIRTUAL_ENV}/bin:$PATH

RUN microdnf install -y dnf openssl-devel && dnf install -y \
       git gcc g++ tar gcc-toolset-13 automake libtool zlib-devel libjpeg-devel\
       openblas-devel python${PYTHON_VERSION}-devel python${PYTHON_VERSION}-pip \
    && dnf clean all \
    && python${PYTHON_VERSION} -m venv ${VIRTUAL_ENV} \
    && python -m pip install -U pip uv \
    && uv pip install wheel build setuptools 'cmake<4' cython \
    && && libjpeg-devel nodejs


# # below env variables are populated in /etc/pim/hmc_agent.conf
ENV HMC_IP=${HMC_IP}
ENV HMC_USERNAME=${HMC_USERNAME}
ENV HMC_PASSWORD=${HMC_PASSWORD}

WORKDIR /hmc_server

COPY server.py /hmc_server/
COPY pyproject.toml /hmc_server/

RUN uv sync

ENTRYPOINT [ "uv", "run", "/hmc_server/server.py" ]
