ARG BASE_UBI_IMAGE_TAG=9.5-1742914212
FROM registry.access.redhat.com/ubi9/ubi-minimal:${BASE_UBI_IMAGE_TAG}

ARG PYTHON_VERSION=3.12

ENV VIRTUAL_ENV=/opt/venv
ENV PATH=${VIRTUAL_ENV}/bin:$PATH

RUN microdnf install -y dnf openssl-devel && dnf install -y \
       openblas-devel python${PYTHON_VERSION}-devel python${PYTHON_VERSION}-pip \
    && dnf clean all \
    && python${PYTHON_VERSION} -m venv ${VIRTUAL_ENV} \
    && python -m pip install -U pip uv \
    && uv pip install wheel build setuptools 'cmake<4' cython \
    && libjpeg-devel nodejs

ENV OLLAMA_MODEL=${OLLAMA_MODEL}

WORKDIR /hmc_agent

COPY agent.py hmc.py /hmc_agent/
COPY pyproject.toml /hmc_agent/

RUN uv sync

ENTRYPOINT [ "uv", "run", "/hmc_agent/agent.py" ]
