FROM quay.io/<account id>/pim:base

COPY vllm/llm_config.sh /usr/bin/
COPY vllm/llm_readiness.sh /usr/bin/
COPY utility/download_model.py /usr/bin/

COPY vllm/llm_config.service /etc/systemd/system
COPY vllm/llm_readiness.service /etc/systemd/system

RUN systemctl unmask llm_config.service
RUN systemctl unmask llm_readiness.service

RUN systemctl enable llm_config.service
RUN systemctl enable llm_readiness.service

COPY vllm/vllm.container /usr/share/containers/systemd
