FROM quay.io/fedora/fedora-bootc:43

RUN dnf -y install cloud-init && \
    ln -s ../cloud-init.target /usr/lib/systemd/system/default.target.wants && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}
COPY usr/ /usr/

COPY base.service /etc/systemd/system

RUN systemctl unmask base.service
RUN systemctl enable base.service
